---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-debian
    - geerlingguy.docker

  tasks:
    - name: Install some helpful utilities.
      apt:
        name:
          - git
          - wget
          - curl
          - emacs
          - cowsay
        state: installed
    - name: adding vagrant to group docker
      user:
        name: vagrant
        groups: docker
        append: yes
    - name: Install python docker
      pip:
        name:
          - docker
          - docker-compose
